### PR TITLE
Add support for createSubscription

### PR DESCRIPTION
**Pull request by tomtwo**
It's now possible to also create subscriptions using this same component:

https://github.com/paypal/paypal-smart-payment-buttons/pull/14

This pull request allows a `createSubscription` prop to override the default `createOrder` callback, enabling us to use this button to facilitate subscriptions.

### CODE REVIEW

**Comment by carnufex** [comment]
Any chance this is being merged anytime soon?

I'm looking to implement subscriptions and don't know how to compile this to a node_module.

**Comment by g-g-n** [comment]
Me too waiting for the merge...

**Comment by Luehang** [comment]
Hi,

This pull request has been reviewed and merge.  Thanks for contributing.

```sh
$ npm install react-paypal-button-v2@2.6.0 --save
```

or

```sh
$ yarn add react-paypal-button-v2@2.6.0
```

And follow the section for [Subscription Example](https://github.com/Luehang/react-paypal-button-v2#subscription-example-usage).

**Comment by tomtwo** [comment]
Thanks for merging this in. 🔥

A note to anyone who wants to use this alongside the regular `createOrder` button: they do _not_ play nicely together on the PayPal side. Even after cleaning up the old PayPal globals, PayPal code will crash at different points (seemingly) randomly. For example I've seen the checkout flow on PayPal succeed, and then crash on returning back to our app before calling the `onApprove` callback. Our solution was to save all local state and hard refresh the page when switching the button out.

**Pull request merged**
